type Person {
  id: ID!
  firstName: String
  lastName: String
  username: String!
  email: String!
}

input NewPerson {
  username: String!
  email: String!
  firstName: String
  lastName: String
  cityId: ID!
}

type City {
  id: ID!
  name: String!
}

type State {
  id: ID!
  name: String!
}

type Cuisine {
  id: ID!
  name: String!
}

type Restaurant {
  id: ID!
  name: String!
  address: String!
}

input NewRestaurant {
  name: String!
  address: String!
  cityId: ID!
  cuisineId: ID!
}

type Review {
  id: ID!
  createdAt: AWSDateTime!
  rating: Int!
  body: String
}

input NewReview {
  rating: Int!
  body: String
  personId: ID!
  restaurantId: ID!
}

type ReviewRating {
  id: ID!
  thumbsUp: Boolean!
  reviewDate: AWSDateTime!
}

input NewReviewRating {
  thumbsUp: Boolean!
  personId: ID!
  reviewId: ID!
}

type EventBridgeReponse {
  result: String!
}

type Query {
  getPerson(id: ID!): Person
  getFriends(personId: ID!): [Person!]
  getFriendsOfFriends(personId: ID!): [Person!]
  findPathBetweenPeople(person1Id: ID!, person2Id: ID!): String
  highestRatedRestaurantByCuisine(personId: ID!, cuisineIds: [ID!]!): Restaurant
  highestRatedRestaurants(personId: ID!): [Restaurant!]
  newestRestaurantReviews(restaurantId: ID!): [Review!]
  restaurantsByFriendsRecommendation(personId: ID!): [Restaurant!]
  restaurantsByFriendsReviewRatingss(personId: ID!): [Restaurant!]
  restaurantsRatedOrReviewedByFriendsinXDays(
    personId: ID!
    numDays: Int! = 10
  ): [Restaurant!]
}

type Mutation {
  addPerson(newPerson: NewPerson!): EventBridgeReponse
  addUpdateFirstName(personId: ID!, firstName: String!): EventBridgeReponse
  addUpdateLastName(personId: ID!, lastName: String!): EventBridgeReponse
  deletePerson(id: ID!): EventBridgeReponse
  addCity(name: String!, stateId: ID!): EventBridgeReponse
  updateCityName(id: ID!, newName: String!): EventBridgeReponse
  deleteCity(id: ID!): EventBridgeReponse
  addState(name: String!): EventBridgeReponse
  updateStateName(id: ID!, newName: String!): EventBridgeReponse
  deleteState(id: ID!): EventBridgeReponse
  addCuisine(name: String!): EventBridgeReponse
  updateCuisineName(id: ID!, newName: String!): EventBridgeReponse
  deleteCuisine(id: ID!): EventBridgeReponse
  addRestaurant(newRestaurant: NewRestaurant!): EventBridgeReponse
  updateRestaurantName(id: ID!, newName: String!): EventBridgeReponse
  updateRestaurantAddress(id: ID!, newAddress: String!): EventBridgeReponse
  deleteRestaurant(id: ID): EventBridgeReponse
  addReview(newReview: NewReview!): EventBridgeReponse
  addReviewRating(newReviewRating: NewReviewRating!): EventBridgeReponse
  addFriendsEdge(fromId: ID!, toId: ID!): EventBridgeReponse
}

type schema {
  query: Query
  mutation: Mutation
}
